### ISSUE TITLE
linux build issue: exberry_adapter/bot.egg-info

### ISSUE THREAD

**Issue by lucianojoublanc-da** [digital-asset/da-marketplace#160]
`make package` fails on a52f143

I suspect this is specific to linux (Ubuntu 20.04)

```
/home/luciano/.poetry/lib/poetry/_vendor/py2.7/subprocess32.py:149: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
  "program uses threads.", RuntimeWarning)
Traceback (most recent call last):
  File "/home/luciano/.poetry/bin/poetry", line 12, in <module>
    from poetry.console import main
  File "/home/luciano/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/luciano/.poetry/lib/poetry/console/application.py", line 7, in <module>
    from .commands import AboutCommand
  File "/home/luciano/.poetry/lib/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/home/luciano/.poetry/lib/poetry/console/commands/check.py", line 1, in <module>
    from poetry.poetry import Poetry
  File "/home/luciano/.poetry/lib/poetry/poetry.py", line 11, in <module>
    from .json import validate_object
  File "/home/luciano/.poetry/lib/poetry/json/__init__.py", line 4, in <module>
    import jsonschema
  File "/home/luciano/.poetry/lib/poetry/_vendor/py2.7/jsonschema/__init__.py", line 32, in <module>
    from pkg_resources import get_distribution
ImportError: No module named pkg_resources
mkdir .dev
daml build > .dev/daml_build.log
SDK 1.8.1 has been released!
See https://github.com/digital-asset/daml/releases/tag/v1.8.1 for details.

cd triggers && daml build
SDK 1.8.1 has been released!
See https://github.com/digital-asset/daml/releases/tag/v1.8.1 for details.

Compiling da-marketplace-triggers to a DAR.
Created .daml/dist/da-marketplace-triggers-0.1.8.dar
cp triggers/.daml/dist/da-marketplace-triggers-0.1.8.dar target/da-marketplace-triggers-0.1.8.dar
cp .daml/dist/da-marketplace-0.1.8.dar target/da-marketplace-model-0.1.8.dar
daml codegen js .daml/dist/da-marketplace-0.1.8.dar -o daml.js
SDK 1.8.1 has been released!
See https://github.com/digital-asset/daml/releases/tag/v1.8.1 for details.

Generating 057eed1fd48c238491b8ea06b9b5bf85a5d4c9275dd3f6183e0e6b01730cc2ba
Generating 40f452260bef3f29dede136108fc08a88d5a5250310281067087da6f0baddff7
Generating 518032f41fd0175461b35ae0c9691e08b4aea55e62915f8360af2cc7a1f2ba6c
Generating da-marketplace-0.1.8 (hash: 5ac556498550429862e58cc22840a3298a98e048b4c4c9f7e7429aac62bf8a13)
Generating 6839a6d3d430c569b2425e9391717b44ca324b88ba621d597778811b2d05031d
Generating 6c2c0667393c5f92f1885163068cd31800d2264eb088eb6fc740e11241b2bf06
Generating 733e38d36a2759688a4b2c4cec69d48e7b55ecc8dedc8067b815926c917a182a
Generating 76bf0fd12bd945762a01f8fc5bbcdfa4d0ff20f8762af490f8f41d6237c6524f
Generating 8a7806365bbd98d88b4c13832ebfa305f6abaeaf32cfa2b7dd25c4fa489b79fb
Generating 93487fde922c51290fd8209c710b934b9900f46ea4557936a9851a35c95b7fd8
Generating 99a2705ed38c1c26cbb8fe7acf36bbf626668e167a33335de932599219e0a235
Generating ac9677ef0dcbb2cac09a2f9c90aae9896f225a20a34bb1f9248ffb8c4bec7594
Generating b699edfd730564f95a69ca6e1c97d2d3c3303f06768a2c2bd3ba012234967fa6
Generating bfcd37bd6b84768e86e432f5f6c33e25d9e7724a9d42e33875ff74f6348e733f
Generating c1f1f00558799eec139fb4f4c76f95fb52fa1837a5dd29600baa1c8ed1bdccfd
Generating cc348d369011362a5190fe96dd1f0dfbc697fdfd10e382b9e9666f0da05961b7
Generating d14e08374fc7197d6a0de468c968ae8ba3aadbf9315476fd39071831f5923662
Generating d58cf9939847921b2aab78eaa7b427dc4c649d25e6bee3c749ace4c3f52f5c97
Generating e22bce619ae24ca3b8e6519281cb5a33b64b3190cc763248b4c3f9ad5087a92c
Generating e491352788e56ca4603acc411ffe1a49fefd76ed8b163af86cf5ee5f4c38645b
cd ui && yarn install
yarn install v1.22.5
info No lockfile found.
[1/4] Resolving packages...
warning semantic-ui-react > react-popper > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning @types/dotenv@8.2.0: This is a stub types definition. dotenv provides its own type definitions, so you do not need this installed.
warning react-scripts > eslint-loader@3.0.3: This loader has been deprecated. Please use eslint-webpack-plugin
warning react-scripts > fsevents@2.1.2: "Please update to latest v2.3 or v2.2"
warning react-scripts > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning react-scripts > webpack-dev-server > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning react-scripts > babel-jest > @jest/transform > jest-haste-map > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning react-scripts > jest-environment-jsdom-fourteen > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning react-scripts > jest-environment-jsdom-fourteen > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi@15.1.1: Switch to 'npm install joi'
warning react-scripts > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning react-scripts > jest-environment-jsdom-fourteen > jsdom > request > har-validator@5.1.5: this library is no longer supported
warning react-scripts > resolve-url-loader > rework > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning react-scripts > webpack-dev-server > http-proxy-middleware > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning react-scripts > webpack-dev-server > http-proxy-middleware > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
warning react-scripts > workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/topo > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
warning react-scripts > jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning react-scripts > jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning react-scripts > workbox-webpack-plugin > workbox-build > strip-comments > babel-plugin-transform-object-rest-spread > babel-runtime > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-scripts > jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.3.1: The platform "linux" is incompatible with this module.
info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 33.03s.
cd ui && yarn build
yarn run v1.22.5
$ react-scripts build
Creating an optimized production build...
Compiled with warnings.

./src/components/RoleSelectScreen.tsx
  Line 10:10:  'ArrowRightIcon' is defined but never used  @typescript-eslint/no-unused-vars

./src/components/Investor/Investor.tsx
  Line 25:48:  'UserIcon' is defined but never used  @typescript-eslint/no-unused-vars

./src/components/common/WalletTransaction.tsx
  Line 35:59:  'providers' is assigned a value but never used  @typescript-eslint/no-unused-vars

./src/components/Broker/Broker.tsx
  Line 65:11:  'allProviders' is assigned a value but never used  @typescript-eslint/no-unused-vars

./src/components/LoginScreen.tsx
  Line 6:24:  'Header' is defined but never used  @typescript-eslint/no-unused-vars
  Line 6:38:  'Popup' is defined but never used   @typescript-eslint/no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

File sizes after gzip:

  299.56 KB  build/static/js/2.3ecf77aa.chunk.js
  94.84 KB   build/static/css/2.eae91454.chunk.css
  24.46 KB   build/static/js/main.362dd775.chunk.js
  5.69 KB    build/static/css/main.d76a402d.chunk.css
  777 B      build/static/js/runtime-main.e8337ad5.js

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  yarn global add serve
  serve -s build

Find out more about deployment here:

  bit.ly/CRA-deploy

Done in 48.01s.
cd ui && zip -r da-marketplace-ui-0.1.8.zip build
  adding: build/ (stored 0%)
  adding: build/favicon.png (stored 0%)
  adding: build/asset-manifest.json (deflated 73%)
  adding: build/precache-manifest.caed83581237fc26daf528ca1c80a4df.js (deflated 69%)
  adding: build/manifest.json (deflated 39%)
  adding: build/index.html (deflated 53%)
  adding: build/service-worker.js (deflated 44%)
  adding: build/static/ (stored 0%)
  adding: build/static/css/ (stored 0%)
  adding: build/static/css/main.d76a402d.chunk.css.map (deflated 89%)
  adding: build/static/css/2.eae91454.chunk.css (deflated 82%)
  adding: build/static/css/2.eae91454.chunk.css.map (deflated 83%)
  adding: build/static/css/main.d76a402d.chunk.css (deflated 83%)
  adding: build/static/js/ (stored 0%)
  adding: build/static/js/main.362dd775.chunk.js (deflated 79%)
  adding: build/static/js/runtime-main.e8337ad5.js (deflated 52%)
  adding: build/static/js/2.3ecf77aa.chunk.js.map (deflated 75%)
  adding: build/static/js/2.3ecf77aa.chunk.js (deflated 71%)
  adding: build/static/js/main.362dd775.chunk.js.map (deflated 77%)
  adding: build/static/js/runtime-main.e8337ad5.js.map (deflated 65%)
  adding: build/static/js/2.3ecf77aa.chunk.js.LICENSE.txt (deflated 69%)
  adding: build/static/media/ (stored 0%)
  adding: build/static/media/BrownStd-Regular.83f524a7.otf (deflated 48%)
  adding: build/static/media/icons.962a1bf3.svg (deflated 66%)
  adding: build/static/media/outline-icons.82f60bd0.svg (deflated 66%)
  adding: build/static/media/brand-icons.13db00b7.eot (deflated 34%)
  adding: build/static/media/brand-icons.a1a749e8.svg (deflated 68%)
  adding: build/static/media/outline-icons.701ae6ab.eot (deflated 52%)
  adding: build/static/media/flags.9c74e172.png (deflated 1%)
  adding: build/static/media/brand-icons.a046592b.woff (deflated 0%)
  adding: build/static/media/outline-icons.cd6c777f.woff2 (stored 0%)
  adding: build/static/media/brand-icons.e8c322de.woff2 (deflated 0%)
  adding: build/static/media/icons.0ab54153.woff2 (deflated 0%)
  adding: build/static/media/lock.a10822e8.svg (deflated 67%)
  adding: build/static/media/icons.b87b9ba5.ttf (deflated 51%)
  adding: build/static/media/BrownStd-Light.7e848743.otf (deflated 48%)
  adding: build/static/media/marketplace.6c14a93a.svg (deflated 38%)
  adding: build/static/media/outline-icons.ad97afd3.ttf (deflated 52%)
  adding: build/static/media/brand-icons.c5ebe0b3.ttf (deflated 34%)
  adding: build/static/media/BrownStd-Bold.ad9eb21d.otf (deflated 49%)
  adding: build/static/media/icons.8e3c7f55.eot (deflated 51%)
  adding: build/static/media/outline-icons.ef60a4f6.woff (deflated 0%)
  adding: build/static/media/icons.faff9214.woff (deflated 0%)
mv ui/da-marketplace-ui-0.1.8.zip target/da-marketplace-ui-0.1.8.zip
rm -r ui/build
cd exberry_adapter && poetry install && poetry build
/home/luciano/.poetry/lib/poetry/_vendor/py2.7/subprocess32.py:149: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
  "program uses threads.", RuntimeWarning)
Traceback (most recent call last):
  File "/home/luciano/.poetry/bin/poetry", line 12, in <module>
    from poetry.console import main
  File "/home/luciano/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/luciano/.poetry/lib/poetry/console/application.py", line 7, in <module>
    from .commands import AboutCommand
  File "/home/luciano/.poetry/lib/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/home/luciano/.poetry/lib/poetry/console/commands/check.py", line 1, in <module>
    from poetry.poetry import Poetry
  File "/home/luciano/.poetry/lib/poetry/poetry.py", line 11, in <module>
    from .json import validate_object
  File "/home/luciano/.poetry/lib/poetry/json/__init__.py", line 4, in <module>
    import jsonschema
  File "/home/luciano/.poetry/lib/poetry/_vendor/py2.7/jsonschema/__init__.py", line 32, in <module>
    from pkg_resources import get_distribution
ImportError: No module named pkg_resources
make: *** [Makefile:123: exberry_adapter/bot.egg-info] Error 1
```

**Comment by lucianojoublanc-da** [comment]
Surprisingly the UI does appear to work fine, at least for issuance.

I suspect this may be due to missing dependencies (see README); you can see it's using python 2.7 in the log files.

**Comment by lucianojoublanc-da** [comment]
This turned out to be an issue with the deps file in linux. Fixed in db0cae1b6.

**Comment by lucianojoublanc-da** [comment]
Reminder to self: @brian-weir noted that the caret syntax will allow python 3.9 versions. Soln is to use the tilde to only allow 3.8.x apparently. See poetry docs.
